server:
  port: 3001

spring:
  application:
    name: news
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/news?serverTimezone=GMT%2B8&characterEncoding=utf-8&useAffectedRows=true
    username: root
    password: 123456
#  mysql主从复制配置文件
#  shardingsphere:
#    datasource:
#      names: master,slave
#      master:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.194.85:3306/news?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#        username: root
#        password: 690802
#      slave:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.194.47:3306/news?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#        username: root
#        password: 690802
#    masterslave:
#      # 读写分离配置
#      load-balance-algorithm-type: round_robin #轮询
#      name: dataSource
#      master-data-source-name: master
#      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 0
        max-wait: 10ms
  cache:
    redis:
      time-to-live: 1800000 # 设置缓存数据的更新时间30分钟
  mail:
    host: smtp.qq.com
    # 发件人
    username: 1084334584@qq.com
    # 授权码
    password: xtbitoootrzkhgja
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  #允许bean定义覆盖
  main:
    allow-bean-definition-overriding: true
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
news:
  path: E:\JavaProject\news\img\
#  path: /usr/local/java/img/